joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

right_motor_controller:
  type: velocity_controllers/JointVelocityController
  joint: propeller_r_joint
  pid:
    p: 100.0
    i: 0.01
    d: 10.0

left_motor_controller:
  type: velocity_controllers/JointVelocityController
  joint: propeller_l_joint
  pid:
    p: 100.0
    i: 0.01
    d: 10.0
